name: Digital Ocean Depoyment
on: [push]
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          cd ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."